#!/usr/bin/env python3
"""Parametric vase mesh generator.

Generates OBJ meshes for rotational vase-like surfaces with optional
helical/wavy modulation. Meshes are open at the top and closed at the bottom.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass, asdict
from pathlib import Path


@dataclass
class VaseParams:
    name: str
    height: float = 180.0
    base_radius: float = 22.0
    neck_radius: float = 16.0
    lip_radius: float = 20.0
    belly_amp: float = 14.0
    belly_center: float = 0.46
    belly_width: float = 0.24
    vertical_curve: float = 0.0
    waves: int = 12
    wave_amp: float = 0.10
    wave_z_falloff: float = 0.25
    twist: float = 8.0
    twist_curve: float = 0.0
    skew_wave: float = 0.0
    seed_phase: float = 0.0


def smoothstep(x: float) -> float:
    x = max(0.0, min(1.0, x))
    return x * x * (3.0 - 2.0 * x)


def base_profile(z: float, p: VaseParams) -> float:
    # Smoothly interpolate base->neck->lip and add a gaussian belly.
    neck_mix = smoothstep(z)
    linear = (1.0 - neck_mix) * p.base_radius + neck_mix * p.neck_radius
    lip_bloom = (p.lip_radius - p.neck_radius) * smoothstep((z - 0.86) / 0.14)
    belly = p.belly_amp * math.exp(-((z - p.belly_center) / max(1e-6, p.belly_width)) ** 2)
    vertical_bias = p.vertical_curve * (z - 0.5)
    return max(1e-3, linear + lip_bloom + belly + vertical_bias)


def wave_envelope(z: float, p: VaseParams) -> float:
    # stronger in middle, can fade near top and bottom.
    center = math.sin(math.pi * z) ** 0.7
    fade_edges = smoothstep((z - p.wave_z_falloff) / (1.0 - 2.0 * p.wave_z_falloff))
    return center * fade_edges


def twist_phase(z: float, p: VaseParams) -> float:
    return p.seed_phase + p.twist * z + p.twist_curve * z * z


def radius(theta: float, z: float, p: VaseParams) -> float:
    r0 = base_profile(z, p)
    env = wave_envelope(z, p)
    harmonic = math.cos(p.waves * theta + twist_phase(z, p))
    skew = p.skew_wave * math.sin((p.waves // 2 + 1) * theta - 0.7 * twist_phase(z, p))
    mod = 1.0 + p.wave_amp * env * (harmonic + skew)
    return max(1e-3, r0 * mod)


def generate_vase_mesh(p: VaseParams, n_theta: int = 180, n_z: int = 200):
    if n_theta < 3:
        raise ValueError("n_theta must be >= 3")
    if n_z < 2:
        raise ValueError("n_z must be >= 2")
    vertices: list[tuple[float, float, float]] = []
    faces: list[tuple[int, int, int]] = []

    for iz in range(n_z + 1):
        z01 = iz / n_z
        z = z01 * p.height
        for it in range(n_theta):
            th = 2.0 * math.pi * (it / n_theta)
            r = radius(th, z01, p)
            vertices.append((r * math.cos(th), r * math.sin(th), z))

    def idx(it: int, iz: int) -> int:
        return iz * n_theta + (it % n_theta)

    # side quads split into triangles
    for iz in range(n_z):
        for it in range(n_theta):
            a = idx(it, iz)
            b = idx(it + 1, iz)
            c = idx(it, iz + 1)
            d = idx(it + 1, iz + 1)
            faces.append((a, c, b))
            faces.append((b, c, d))

    # bottom cap (closed)
    bottom_center_idx = len(vertices)
    vertices.append((0.0, 0.0, 0.0))
    for it in range(n_theta):
        a = idx(it, 0)
        b = idx(it + 1, 0)
        faces.append((bottom_center_idx, b, a))

    return vertices, faces


def write_obj(path: Path, vertices, faces) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("# Generated by vasegen.py\n")
        for x, y, z in vertices:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for a, b, c in faces:
            f.write(f"f {a+1} {b+1} {c+1}\n")


def write_manifest(path: Path, presets: list[VaseParams]) -> None:
    payload = [asdict(p) for p in presets]
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def default_presets() -> list[VaseParams]:
    return [
        VaseParams(name="spiral_ribbed", waves=14, wave_amp=0.16, twist=12.0, skew_wave=0.10, belly_amp=11.0),
        VaseParams(name="soft_organic", waves=4, wave_amp=0.09, twist=3.5, skew_wave=0.55, belly_amp=7.0, neck_radius=18, lip_radius=19),
        VaseParams(name="fluted_classic", waves=18, wave_amp=0.11, twist=1.5, skew_wave=0.00, belly_amp=10.0, base_radius=20),
        VaseParams(name="tall_twist", height=240, waves=22, wave_amp=0.08, twist=9.0, belly_amp=16.0, belly_center=0.30, neck_radius=14, lip_radius=16),
        VaseParams(name="petal_lip", waves=12, wave_amp=0.15, twist=6.0, skew_wave=0.25, belly_amp=9.0, lip_radius=30),
        VaseParams(name="minimal_wavy", waves=3, wave_amp=0.07, twist=2.0, skew_wave=0.45, belly_amp=5.5, base_radius=18, neck_radius=17, lip_radius=18),
    ]


def resolve_preset(name: str) -> VaseParams:
    for p in default_presets():
        if p.name == name:
            return p
    raise KeyError(f"Unknown preset '{name}'")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Generate parametric vase meshes (OBJ).")
    ap.add_argument("--preset", default="all", help="Preset name or 'all'")
    ap.add_argument("--out", default="generated", help="Output directory")
    ap.add_argument("--theta", type=int, default=180, help="Radial resolution")
    ap.add_argument("--z", type=int, default=200, help="Vertical resolution")
    ap.add_argument("--list", action="store_true", help="List presets and exit")
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    presets = default_presets()

    if args.list:
        print("Available presets:")
        for p in presets:
            print(f" - {p.name}")
        return

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    chosen = presets if args.preset == "all" else [resolve_preset(args.preset)]
    for p in chosen:
        v, f = generate_vase_mesh(p, n_theta=args.theta, n_z=args.z)
        path = out_dir / f"{p.name}.obj"
        write_obj(path, v, f)
        print(f"Wrote {path} | vertices={len(v)} faces={len(f)}")

    write_manifest(out_dir / "presets_manifest.json", chosen)


if __name__ == "__main__":
    main()
